### ISSUE TITLE
Could you please share the metrics code about PSNR, SSIM and LPIPS?

### ISSUE THREAD

**Issue by Zdafeng** [ykdai/Flare7K#4]

**Comment by Zdafeng** [comment]
We test the pretrained models of uformer in real world dataset by using the PSNR of basicsr, and the PSNR are 26.22dB and 26.58dB with/without reflection model. However, the PSNR of uformer is 26.98dB in table 2. So, could you please release the metric code that used in table 2?

**Comment by ykdai** [comment]
We have uploaded a evaluate.py and you can have a test. Besides, lower PSNR is caused by line 133 in the file `basicsr\utils\flare_util.py`, please use the default setting of the max diameter (1.5 rather than 0.5). We have fixed it in the code. Then, you will get 26.98dB as the final result. 

If you found this solution helpful, it would mean a lot to us if you could leave a star on our GitHub repository : )
